# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
# default_language_version:
#   python: python3.9

repos:
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        name: Format code (black)

  - repo: https://github.com/timothycrosley/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: Sort dependencies (isort)
        files: \.py$
        additional_dependencies: ["toml"]

  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      # - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
      - id: check-merge-conflict
        additional_dependencies: ["flake8-docstrings", "darglint"]
